function str = export_gauss(start,stop,steps,file)
%***************************************************************************
%* str = export_gauss(start,stop,steps,file)                               *
%*                                                                         *
%*   Speichert Gauss Quadraturpunkte und Gewichte in einer c++ Datei.      *
%*                                                                         *
%*   start - Beginn des Intervalls fuer die GaussQuadratur                 *
%*   stop - Ende des Intervalls [start stop]                               *
%*   steps - Vektor mit den Anzahlen der Quadraturpunkte                   *
%*   file - gibt den Namen fuer die Datei an in der Code gespeichert wird  *
%*                                                                         *
%*-------------------------------------------------------------------------*
%*  Beispiel:                                                              *
%*                                                                         *
%*  > export_gauss(0, 1, [1 2 4], 'gauss.hpp')                             *
%*                                                                         *
%*  Erstellt die Datei 'gauss.hpp', in der sich der Code fuer die          *
%*  Konstanten GAUSS_SIZE und GAUSS_NODES befindet. Dabei werden die       *
%*  Gausspunkte und -gewichte des Intervalls [0,1] fuer 1,2 und 4          * 
%*  Auswertungsstellen generiert.                                          *
%*                                                                         *
%***************************************************************************
%* Author: Peter Schaefer                             schaeferpm@gmail.com *
%* Version: 1.0  (2012)                                                    *
%***************************************************************************

str = ['/***************************************************************************/' char(10) ...
'/* gauss.hpp                                                               */' char(10) ...
'/*                                                                         */' char(10) ...
'/*   Diese Datei definiert Konstanten fuer die GaussQuadratur              */' char(10) ...
'/*                                                                         */' char(10) ...
'/*   Gaus Auswertungspunkte auf dem Intervall ' ...
             '[' num2str(start) ' ' num2str(stop) ']                        */' char(10) ...
'/*                                                                         */' char(10) ...
'/*   2^$NUM entspricht der Anzahl der Auswertungspunkte                    */' char(10) ...
'/*                                                                         */' char(10) ...
'/*   Anzahl der Punkte:    GAUSS_SIZE[$NUM]                                */' char(10) ...
'/*   Auswertungstellen:    GAUSS_NODES[$NUM][$I].n  ($I aktuelle Position) */' char(10) ...
'/*   Gewichte:             GAUSS_NODES[$NUM][$I].w  ($I aktuelle Position) */' char(10) ...
'/*                                                                         */' char(10) ...
'/*                                                                         */' char(10) ...
'/*   Beispiel:                                                             */' char(10) ...
'/*                                                                         */' char(10) ...
'/*   > double sol;                                                         */' char(10) ...
'/*   > for(int i=0;i<GAUSS_SIZE[3];++i)                                    */' char(10) ...
'/*   >    sol += sin(GAUSS_NODES[3][i].n) * GAUSS_NODES[3][i].w;           */' char(10) ...
'/*                                                                         */' char(10) ...
'/***************************************************************************/' char(10) ...
'/* Author: Peter Schaefer                             schaeferpm@gmail.com */' char(10) ...
'/* Version: 1.0  (2012)                                                    */' char(10) ...
'/***************************************************************************/' char(10) ...
char(10) ...
'#ifndef GAUSS_NODES_' char(10) ...
'#define GAUSS_NODES_' char(10) ...
char(10) ...
'typedef struct _gauss {' char(10) ...
'	double n;' char(10) ...
'	double w;' char(10) ...
'} gauss;' char(10) ...
char(10)];

preci = 21;
str2 =['gauss GAUSS_NODES[][' num2str(max(steps)) '] = {' char(10)];
str1 =['double GAUSS_SIZE[] = { '];

for i = steps(1:end)
  str1 = [str1 num2str(i) ', '];
  str2 = [str2 '{' char(10)];
  [n w] = gauss(i,start,stop);
  for j = 1:length(n)
    str2 = [str2 char(9) '{ ' num2str(n(j),preci) ', ' num2str(w(j),preci) ' },' char(10)];
  end
  str2 = [str2(1:end-2) '},' char(10)];
end
str1 = [str1(1:end-2) ' };' char(10)];
str2 = [str2(1:end-2) '};' char(10)];
str = [str str1 char(10) str2 char(10) '#endif' char(10)];

fid = fopen(file,'w');
fprintf(fid,'%s',str);
fclose(fid);
end
